### ISSUE TITLE
tera won't work

### ISSUE THREAD

**Issue by lidel97** [NicoFannelli/TeraOpcodesEU#2]
with this protocol, tera won't work. i installed in the properly folder

**Comment by NicoFannelli** [comment]
Strange... it works for me

**Comment by lidel97** [comment]
i tried several times, game stop working immediately, with old opcodes game does not have issues. of course i have deleted the old ones , or please write how you do to make them working ( i mean the folder, etc. ) . Btw i have followed the usual instructions found in another modules ( about where to add the new opcodes)

**Comment by NicoFannelli** [comment]
Just drop them on tera-data/map folder. Adding opcodes only wont make tera stop working.
Maybe you have installed some outdated or corrupted mod.

**Comment by lidel97** [comment]
all mods are updated and work correctly
